name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (small change)
        - Medium (moderate effort)
        - High (significant effort)
        - Unknown

  - type: checkboxes
    id: would-implement
    attributes:
      label: Would you be willing to implement this feature?
      options:
        - label: Yes, I would like to implement this feature
        - label: I would need guidance but could try
        - label: I would prefer someone else implement this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context, mockups, or screenshots about the feature request here.
        
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
